spring.profiles.active=local

spring.application.name=disaster-ar

server.port=8080

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

file.upload.dir=uploads/maps
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# DevTools
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
